version: "3"
services:
    front:
        build: Diagnostique.FO/.
        ports:
            - "8081:80"
        depends_on:
            - back
    back:
        build: Diagnostique.BO/.
        expose:
           - "80"
        ports:
           - "8082:80"
        depends_on:
           - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "myPass@@"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"